name: Build and Upload Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project for Windows
        run: pnpm build -- --win

      - name: Upload Windows NSIS installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElectronGFNWindowsInstaller
          path: dist/*.exe

      - name: Upload Windows ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElectronGFNWindowsZip
          path: dist/*.zip
